### ISSUE TITLE
How to apply styling to all descendants/extensions of a base class?

### ISSUE THREAD

**Issue by renehamburger** [LearnBoost/stylus#1775]
With the following styles, is there an easier way to apply the final declaration to `.message` and all its descendants, some of which might even be unknown at the time of writing these styles?

```sass
.message
  border: 1px solid black

.message--warning
  @extends .message
  border-color: yellow

.message--error
  @extends .message
  border-color: red

.hideMessages
  .message, .message--warning, .message--error
    display: none
```

It would be great to have a shortcut that expands to a list of all descendants.

A possible work-around is this:

```sass
$messageTypes = (warning yellow) (error red)

allMessages()
  for type in $messageTypes
    .message--{type[0]}
      if typeof(block) == 'block'
        {block}
      else
        @extend .message
        color: type[1]

.message
  border: 1px solid black

allMessages(true)

.hideMessages
  +allMessages()
    display: none
```

The advantage is that there's only one list of descendants, which can be re-used in several places. But it still wouldn't stop anyone from defining yet another descendant somewhere else, so it's still prone to errors.

**Comment by renehamburger** [comment]
Here's a more generic solution that can be used throughout a project. (It's a bit elaborate as I couldn't decide whether the arguments should be compact lists or explicit hashes, so this supports both.)

```css
/* A mixin for defining all extensions of a base class
 - obj can have either of two forms:
     obj = baseClass (listOfExtensions)
     obj = { base: baseClass, extensions: (listOfExtensions) }
 - listOfExtensions can either be a list of names or a list of objects
   containing the names and properties
     listOfExtensions = (name1 name2 ...)
     listOfExtensions = ({name: name1, prop: properties1}, ...)
   Though defining the extension properties explicitly may be preferrable
   to defining it through a hash.
*/
define(obj)
  if typeof(obj) == 'ident'
    obj = {base: obj[0], extensions:obj[1]}
  for extension in obj.extensions
    if typeof(extension) == 'object'
      .{obj.base}--{extension.name}
        @extend .{obj.base}
        prop = extension.prop
        {prop}
    else
      .{obj.base}--{extension}
        @extend .{obj.base}

/* A block mixin for styling all extensions of a base class
 - obj as above
 - includeBase determines if the base class should also be styled
*/
all(obj, includeBase = true)
  if typeof(obj) == 'ident'
    obj = {base: obj[0], extensions:obj[1]}
  if includeBase
    .{obj.base}
       {block}
  for extension in obj.extensions
    if typeof(extension) == 'object'
      extension = extension.name
    .{obj.base}--{extension}
      {block}
```

Here's the example from above 
```css
.message
  border: 1px solid black

$messages = {
  base: message
  extensions: (
    {
      name: warning,
      prop: {
        border-color: red
      }
    } {
      name: error,
      prop: {
        border-color: yellow
      }
    }
  )
}

define($messages)

.hideMessages
  +all($messages)
    display: none
```
But the following more compact solution is probably preferable:
```css
.message
  border: 1px solid black

$messages = message (warning error)

define($messages)

.message--error
  border-color: red

.message--warning
  border-color: yellow

.hideMessages
  +all($messages)
    display: none
```

In either case, having an internal Stylus solution for this would simplify things a lot. Until then this might be helpful work-around.
