### ISSUE TITLE
Selector interpolation doesn't work properly with trailing comma.

### ISSUE THREAD

**Issue by cssmagic** [LearnBoost/stylus#1801]
> Node: v0.10.26
> Stylus: v0.49.3

## Passed

```css
$sel-multiple = '.a, .b,'
{$sel-multiple}
	display block
```

```css
.a,
.b {
  display: block;
}
```

#### Case 1

```css
$sel-multiple = '.a, .b,'
{$sel-multiple}
	span
		display block
```

```css
.a span,
.b span,
span {
  display: block;
}
```

#### Case 2

```css
$sel-multiple = '.a, .b,'
.wrapper
	{$sel-multiple}
		display block
```

```css
.wrapper .a,
.wrapper .b,
.wrapper {
  display: block;
}
```
