### ISSUE TITLE
interpolations and variables inside media queries

### ISSUE THREAD

**Issue by oinovikov** [LearnBoost/stylus#1805]
Use:
```css
.foo
  for i in 1..2
    @media (min-width: 2**(i+7)px)
      width: 100px*i
```
...looking for:
```css
@media (min-width: 256px) {
  .foo {
    width: 100px;
  }
}
@media (min-width: 512px) {
  .foo {
    width: 200px;
  }
}
```
But yield:
```css
@media (min-width: 2**(i+7)px) {
  .foo {
    width: 100px;
  }
}
@media (min-width: 2**(i+7)px) {
  .foo {
    width: 200px;
  }
}
```
