### ISSUE TITLE
[feature request] rootpath for resource

### ISSUE THREAD

**Issue by inno-v** [LearnBoost/stylus#1818]
Does stylus has something similar to LESS' [rootpath](http://lesscss.org/usage/#command-line-usage-rootpath)?

**Comment by Panya** [comment]
Nope, but you can redefine `url` function to achieve this. For example:
```sass
url(path)
  return unquote('url(' + pathjoin('images/', path) + ')')

body
  background: url('test.png')
```

Yields to:
```css
body {
  background: url(images/test.png);
}
```
