### ISSUE TITLE
Division in property passed to transparent mixins

### ISSUE THREAD

**Issue by darsain** [LearnBoost/stylus#1822]
When property value has a division in it, it is treated differently when passed into a transparent mixin.

Test mixin:

```
test(fraction)
	fraction: fraction
	arguments: arguments
```

Test:

```
.transparent
	test: 10/4
.opaque
	test(10/4)
```

Output:

```css
.transparent {
  fraction: 10;
  arguments: 10/4;
}
.opaque {
  fraction: 2.5;
  arguments: 2.5;
}
```

But multiplication behaves properly:

```
.transparent
	test: 10*0.25
.opaque
	test(10*0.25)
```

Output:

```css
.transparent {
  fraction: 2.5;
  arguments: 2.5;
}
.opaque {
  fraction: 2.5;
  arguments: 2.5;
}
```

By wrapping the division in parentheses it is possible to force calculation so that mixin will receive a proper 1st argument:

```
.transparent
	test: (10/4)
```

But that's just sooo ugly :disappointed:.

I'd at least expect division and multiplication to behave similarly.

---

If this can't be resolved due to some necessary magic when dealing with forward slashes in properties, is it at least possible to cast the whole `arguments` array into a string/node/whatever and evaluate it from inside the mixin?

I've tried composing some convoluted solution using build-in functions but didn't succeed.
