### ISSUE TITLE
+cache insertion order

### ISSUE THREAD

**Issue by connec** [LearnBoost/stylus#1829]
When using a mixin in a selector it is expected that the mixin's properties will be in the right order with the selector's properties, e.g:

```stylus
my-mixin()
  color green

a
  color red
  my-mixin()
  color blue
```
▼
```css
a {
  color: #f00;
  color: #008000;
  color: #00f;
}
```

When using `+cache` however, the cached properties always come after the selector's properties:

```stylus
my-mixin()
  +cache('wut')
    color green

a
  color red
  my-mixin()
  color blue
```
▼
```css
a {
  color: #f00;
  color: #00f;
}
a {
  color: #008000;
}
```

Child selectors behave as expected.

```stylus
my-mixin()
  +cache('wut')
    span
      color green

a
  span
    color red

  my-mixin()

  span
    color blue
```
▼
```css
a span {
  color: #f00;
}
a span {
  color: #008000;
}
a span {
  color: #00f;
}
```
