### ISSUE TITLE
Duplicated selectors when extending into placeholders with media queries

### ISSUE THREAD

**Issue by simbo** [LearnBoost/stylus#1830]
When i do this
```stylus
$foo {
    color: red;
    @media (min-width: 768px) {
        color: blue;
    }
}

.bla {
    @extends $foo;
}
```

and parse it with Stylus 0.49.3, i get this css: 

```css
.bla {
  color: #f00;
}
@media (min-width: 768px) {
  .bla,
.bla {
    color: #00f;
  }
}
```

As you can see, the .bla selector gets duplicated in the mediaquery...

(Excuse me, if this issue is already reported. I searched, but couldn't find it.)
