### ISSUE TITLE
Fonts and data-uri

### ISSUE THREAD

**Issue by monolithed** [LearnBoost/stylus#1834]
```
.foo
	background-image data-uri('./files/icons/unknown.png') // converted to base64

@font-face
	font-family 'sept'
	src data-url('./files/fonts/sept.woff') // not converted to base64!
```

What is the difference between the images and fonts?

I don't like to use third-party plugins like [stylus-font-face](https://www.npmjs.com/package/stylus-font-face) when it can be implemented into the Stylus

**Comment by Panya** [comment]
I think that you font size is bigger that default limit (30 KB). See http://learnboost.github.io/stylus/docs/functions.url.html

**Comment by monolithed** [comment]
![1423239141570](https://cloud.githubusercontent.com/assets/803674/6082666/2f4c2a82-ae34-11e4-8f77-85c910c25e68.png)
![1423239163362](https://cloud.githubusercontent.com/assets/803674/6082671/35601dac-ae34-11e4-9033-fe2d749054dd.png)


The *.woff file was skipped

**Comment by Panya** [comment]
I'm not sure that it's a problem with Stylus. Are you sure that path to the font is correct? I've created an example:
`test.js`
```
var stylus = require('stylus')
  , data = require('fs').readFileSync('test.styl', 'utf-8');

stylus(data)
  .define('data-uri', stylus.url({ limit: false }))
  .render(function(err, css) {
      if (err) throw err;
      console.log(css);
  });
```

`test.styl`
```sass
@font-face
  font-family 'Rub'
  src data-uri('./fonts/rouble.woff')
```

```
node test.js
```

Gives me:
```css
@font-face {
  font-family: 'Rub';
  src: url("data:application/font-woff;base64,d09GRgABAAAAABOEABAAAAAAIugAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAABbAAAABwAAAAcVtDkbEdERUYAAAGIAAAAHAAAAB4AJwAdT1MvMgAAAaQAAABMAAAAYGGWYwdjbWFwAAAB8AAAAGMAAAFSRNA70GN2dCAAAAJUAAAAEAAAABABTwHmZnBnbQAAAmQAAAECAAABcwZZnDdnYXNwAAADaAAAABAAAAAQABcACWdseWYAAAN4AAAMvgAAGJB3DusWaGVhZAAAEDgAAAAzAAAANgRFeWFoaGVhAAAQbAAAACAAAAAkBg8CdWhtdHgAABCMAAAAXAAAAFw7pgYNbG9jYQAAEOgAAAAwAAAAMDqaQR5tYXhwAAARGAAAAB0AAAAgAiQBIm5hbWUAABE4AAABqQAAA9h3V9szcG9zdAAAEuQAAAA4AAAAUAKHAzZwcmVwAAATHAAAAGgAAACWTvV1EgAAAAEAAAAA0MuxmAAAAADDApRiAAAAAMMCnnF4nGNgZGBg4AFiMSBmYmAEQjEgZgHzGAAEkABFeJxjYGY6yTiBgZWBhWkPUxcDA0MPhGa8y2DE8IuBgQkoxQCiWIAkIwMSCIgMCmZwYFBgKGZ6958NqGQfWBishmkPmK3AwAgAnwgMV3icY2BgYGaAYBkGRgYQ8AHyGMF8FgYDIM0BhExAWoGhmGHB//9gViKI9f/x/8X/k6G6wICRjQHOZQTpYWJABYwQqygCLKxs7BycXNw8vHz8AoJCwiKiYpQaiR2Q51IA+j0NGAAAFACEACkAUABkAF0ArgC1eJxdkD1OxDAQhcc4LOQGSBaSLSsUK6/oqVI4kVCaQCg8DT/SrkT2DkhpaFxwlqEzXS6GYJKNttjGM+/N6POzE4BrEuRt+BbiC5P4+0zgr38gB/nyvEkgnNZV70m8sjhzbKwNd9LpmmRRPwaLOup4v4261u9vW8qKufJgF/FWE3Sh5/MpGCpRHdsd4h1zsomTzZyITNgvhP1MYMAvL527RpO8acNDoMErKj0qY3RFYxto9Mog8tbqmJTrR3+1ZL7gzKs1N5cHSheoVAQY40FZQ0OMKvI7Fp1gPDEEnBrlYvBPTERZVEkM7TwarFGTYY01nBM93527pgsVJzW4+Qck6mvkAAAAAAADAAgAAgAQAAH//wADeJzV2FtsHOUZBuD5fdjzcWYP3l2PvTN78npnduzZg9d2dhM7duzEsWNj5+AkDokJcUgICoRTgoCWBFpaCSpRIKGF0ouqpVUrVBoIaRUuKkRAoiQoVFWVqoKqKqIXXLWqijr0nZl/43XaBFXNRSvnn2+ysle7z7zzzTfDNDEvMEzT502/YCJMkrl4hkkpZ5gOrJTvDEMuYClDrcxvmQ7mE6ymhaEYY8dOBCuL1Y+1Hmse6zaso1iPY53Cegnrday3sdwLeFe8o/0y3hE1iurGu0ex779gvsbRGka1o6YvM2cYVjnLNDMJpjl3lvEyPqPGGBfqGSaGX2Lwyww+rg/7Aex7UUOoLtS2Cz29XMEvqOGOpmDAkiNBAT+JUqJUKCX6Cmq5VExn0jnywgRxjCaL67KHv/kqOa49uHNiYuL7r81vlJNttdPkDjJlsfdsKW5/sDb9xBPTtbm1VanqsDJgY7Zh8zXDLsV87yxjZeL4YIZXHF7xulccvxCHVxxecXjF4RWHVxxecXjF4RWHVxxecXjFDS8rvkJm2SC5wqCdcRoG7dTA6TNBr3ZwGg7m70UND66gdpBgwEOsOWIV8JPoAwbWIFFrpFTMkxx5cPXAp7Vq98gdU4dEJ9no1n4WmYzU3KsdtZPBAyOj+bZs6SlykMyIc+Xxh2RSnX7yyenqJnG6JyWxusvTNFMxJsP87gzThQMkYnWtzJQII7FuJMJIhJEIIxFGIoxEGIkwEmEkwkiEkQgjEUaiYSTiHVvxjq2KuW+j+eJRvXidb8hVkNYIqg01q9sGYOtnWMO0GZ9Wrx2Mx7DtaMgXSz391NNzxdNfQL5M0KsixgULhihClnh65g9fzlRnlPG0unsnOaQ99cTMzMzvJ+cqcVmMTJKHSM3hOzA7tE21OVbdu2XLvatI7a2Q0plWLa3wnGWY5ozhmWa+q+dMqOdMgKFQNxRgKMBQgKEAQwGGAgwFGAowFGAowFCAoQBD4UrOuv7VImVUnlrw1EL/3i79/LquCSeYGWvSSRpDlipcydjJbWsJPzFfyK4aGRAXFjzk9oj2NPsN9ubYTs8O0iwd2SiFsuv2k4dJNTnbX9pb7bS1Dt29efPdQ/fwq1PRuBcuO5Cz++CSZ6p6zmr4UCpWbWXOVBipdSMVRiqMVBipMFJhpMJIhZEKIxVGKoxUGKkwUg0jVT+9aLYGLpun2AD92vprXbRKqG7U1bpnHJ4OpmI4hpiwUQkjG54VPax6EPFxZRpSDvthPZjYD6Hm6JsOGKZ6jvIkUxLUEJqZ1UNo2AIhxK8QFEo10lcjVWJEL2XmTndGPss79tg5NuUhaxaPSenUfGGKlLV3nKxdZrVLLtnmde/Zs4c85nO6fWwlu04trSW7PvPHrNZWktg1VZmLtUd7u4/6o9YWSyJBWlssEe5ot7o3XAjwA6FwVHsHCfz8TzgWD+BYFJm1ekZ9xhc3/Cvwr9T9K/CvwL8C/wr8K/CvwL8C/wr8K/CvwL8C/wr8K4a/3tZGddM0TN1MzbCMMFGjDkFXNx2iGdUPv1PvfYp5gVGwH0Htpa4Fw7OvWDaJEn0NpEZYPYSqWoU+tQzV1cRM77JqM1SLewabbE5fwmsjfZsPlLLSwcEtLjJg195sJ8TmtMl+q3bJ6pYdLNvSvsex271IXgn4XV5vPrFmfWVglixoLc5Wh7/VYhEmhgd3dYpCMXus1dHs9Lc2WwShtcUaZY9li/fyQ3wo6/Ox2lsZxrjujGLzgZH7PuZdhAlfVFHMUDXkXoG7UndXwKXAXYG7AncF7grcFbgrcFfgrsBdgbsCd8VwVxpyX6S5L14n9/3LuVdX5L7EBIxjVKLH6OqcB1DlL855+OqcF9NmwkeXXAFP3kmOf/XRnpx019gg2a296GEdea92wtNj59xLS0vk4prZbPCmzWThL2zEZrE3pbfMD2yJtUdKym42amuxk0wG6baFA7cqpfNTk9q7G5Drt2H9G8N6QL/GuyFDc30DfHWzVdcyq/cK9T/oFUUz22ZQrxFspNowrKdaN9TzjJfalirNTd09dnLsgfsrxeKXJtc5yZJDOxVuak4VbdoJm7vXxQVaokuO/Y6lJkv/UHI8Xt7YFg6S7Z86Pc3BsDU5PlHdLXR2KNItdm9LKNiaTBJLiyXqPyLl/14uaec7+dgGPcPPYnMSru1MjvkACcIX4rGklRnmYczXjXkY8zDmYczDmIcxD2MexjyMeRjzMOZhzMOYN4z5hrkzheq7YE63AUoWojVK505ZPx7BhrmTZTijpjF96ccj3TAXcHRgZelgoc9dMdSYQmeDkDEcNOSYDgephvYM+GfHXq5tFTOS0J5cnNhEBrU3F8bGxsiLkUh4QJpcUxltC3BkM1kKhqOzA/JNfCJVnb7//unah8mS3+vSPubCQdXsDc9h8w+4djK9+jyvXw/jihmiBtcbMJ/GG1y7Lpux7KIc9TnLmMWoa0F3bYNr0OjXum+a5rzjyrzF0jzrByOI2t7QaLoUOs8vm16TNWiy4t9z48RX3ZrsynXybC4aXZXeSSa1V14eHx8nP2kPRORMxBWR/J5OO+sit5HZUFt0W7V3Wwfb6XS6ek709p7o+WtHzupseZ80N3ls/rRuLGJTgXEWVztktwTfvGI2twbjPIzzdeM8jPP4gzyM8zDOwzgP4zyM8zDOwzgP4zyM8zDOG8b5hv7bfdm8V+pumGUTtGZo/y3rxu0wtjEthi1n9N2zOMd8hnGOZlfvt8kLZn7TF8wLrG7cgqrSPqzfG5XMSa4+2QbCoUHslQpqX5m2YPNGCpdR0Sru9QQyUcLcfPuGO/ffQ/La+55AV1T7ICpxjr17956fK29KjUrRLNnxx7W+EJdeqG25PSceHvaFOY73rTos5sTZ4fxUxqHfPryHzVEYZ9AVMU+4jGZouMpwleuuMlxluMpwleEqw1WGqwxXGa4yXGW4ynCV4SobrjI9/wOKeatYrLvZmZ4Vblnqlm1wE6lbkrqlzZ5bXm65VxquhfZbtUybbR+9JYDW0GQpwKutJHDo4Mhjm77kJdM27ccRrr1k0T6x9OXaYuvsY96Jny5WFoprhhIFsu+1sTYu3MztGi7vrRWTW0aC/lAzx6U370oWRWWhUKja9WwWsXkYbmlcYjAb9Chmb+1ZmU0JhlLdUIKhhK8qwVCCoQRDCYYSDCUYSjCUYCjBUIKhZBjqndrZcP776Plf76txWnUm/Ta0VzeOGtlUVvTVLmrcRY11W4H21AQ1TtFMImf1ycCSMCNpTr/qlZkALTWkH4tEcdGT6CG9zxyfm1DvIwXtXU9S0Z7vSXgWFxdJc3T1yMgIufVyP89yB2dG9rAuueuQ/h+O5fsPdclkq3aRTGyaXI8s/hKmXzfO9wJzWp8B8vUs/tfnuB41VD/bb57BpeUk9l7nDNZvAnsZu/Fn1zqXe41ZF0tZkc9wyDifV+QTnbKe0JT5YAQBje+peROyhQTvLEx96/hulhQ82q/a3PE+q/ZDSy7ptvvaFt2L/kViqYzPFBW7j9z6a4njYoTj89u3PVrNzWX9bW2E44iPdVbnctXcI2NKmSCjb8DzB/Bswy3oRfPZAE/v4G/8tb/+TCBy2bx11W8FfDSbbMMMoD8TSOj6fuPaHzfUPcY1/yzuNMznLVGaUS+dwzy0GTvphS+8fN0PXeuZU468UT1303Y+dfIrOSJplxar1ep3MvOLU9tWkUWyPSbKk4cfHp84fnxibHJmolY2r+vnsblE56WL/5fz0o2alc4Pn1u9VeySBD55y8QCGdV+vjA8PEx+FNVnpZ1T/etCYZbMkf3BcGxTLT/NJ5PD00eOTA99lCz7PW7t42AoRGelddi8Sk1fOmuI0fP6BjnWR3XqpD9fCdLZJ/FvjfRnKdxl08lPnViKbXrRZ3iNViuesDTcoMLq6IbZ19fMxtp5Vc4d3LjPT27xad+O7oqu92/wrSd/9vkDfdK24dn+iVg8TmbIwXAwWO0e2JdJJsY33nXXxnGtLev2erSPQqHYWtPsHMM072g69z+cw3r+lo19182hb2UOhS/MIR0uz82T7rU7EzlZ6OxemryTHNCeOT0/P08+jAfby3JnMb8qwHoxU24Oh9u3VpXtHd3duRPl8onuv3XkbK6m951+b7dpOgjTSeM5ssg8r+cwWs9hFI7RumPUeOSRxerHWo81j3Ub1lGsx7FOYb2E9TrW21i6o26T1LPnufJsjzdqnD5Hj/uWn+356E2+hwJ7qdXy8/Tl7K0MHtEbmxUyj+zb9NnovlQy897ZUQc5ymuPuk679nUs2fc1ZQcH1vcOze4g+8kcFw5v6HvwVO5EqXQiR1qzmYsI2D8BsaUvyAAAeJxjYGRgYADiZ9c1UuL5bb4yyDO/AIowXPg16z6M/n+YgYE5mmkfkMvBwAQSBQCY+Q5lAHicY2BkYGB695+NgYF57f/D/1cxRzMARVCAOAChigaIAfQAAAAAAAAB9AAAAfQAAANYAJ4CSwBYA10AlQLfAFMCuABbArr/5wL6AEUCgv/JAr4AlwMrAJoCgAAiAmT/zwK9ADQCSP/DAswAvwMRAMgCdwBGA60AvgMmADsAAAAAAAAAAAAAAJ4BKgHSAl4DJAPaBJAFPAXoBpoHTAfoCJIJOgnUCn4LGAvCDEh4nGNgZGBgEGdwYWBiAAFGMMnFAOLeBTEBDl4BSQAAAHicrZG/TgJBEMa/Pf4cmoiAhYmNUxlNDB5YmFCQEFoaITHaEA9ZD8LBkTvQUPkKWtra+gTGyhifxofQYRmQGC1MvM3d/nZuv292ZgFsqTIUZs8BzoUVUngQtmDjWTiGDbwLx2GrdeEE1tShcJLjx8I2ttW9cAox9SK8in1rWziDlNUUzsK2roVzHL/jjCq+wqumyT5lxYpbYQtpPArHsINX4TjHP4QTXOOmcBJpVRG2UVZnwikk1ZPwKk7Vm3AGGasmnEXa8oRzHL9BFQGGmCBEFx46GIGwiwvs8VyEw+OIqcU7CBXU0EDekM+DllSRWWmeNc9X/G3zTlSD4STsep0R7V7sUdFxjqg1oUqtkaeK75P5FVGoIx1e6TYLZjkIdYw5q8+BWoPq4xZTnU09DvtwOQXq2hv7bjiXlBYH/BKXloqYGpVo7lYyZ5lrl5PNcp2YMiIuL8CAXQpcjGMGTnQYdYMBFfKO4/zu8P0sxF7TJrn8jtjb5QZp9E0tPY4FuFxq8aJs6kbk0ih027rvhj0KLk335v7TffjTJf7D9f373f0k+QQhaJhtAAAAeJxtw8kRQEAAALBYRehDDW7WTafqw3jLTASf+5L7k70TQapQqtQarU5vEI0ms8VqszucD/WfB714nFXMTQpAYBCA4de/LJSSkkLJxqcspVi6gmO4hivJ5ruayV9pFjM9Te8OigMDC1MZB7aMHFpWT0dNQgT4SuMwXpJ/4lKSEhMSPOJR/AQt6YaKTELvk8nGysIksVssZgbaL30Ch1gOwg==");
}
```
