### ISSUE TITLE
issues within @media rules

### ISSUE THREAD

**Issue by OctoD** [LearnBoost/stylus#1836]
I found two issues using media queries, block and placeholders into media queries.

* Callin `current-media()` bif inside a mixin which yelds a media-query with a block inset, will return an empty string

* Extending nested placeholders inside a media query will not be considered unless the selector which is using the `@extend` directive has a css property, or another css selector is already using the `@extend` directive for that placeholder.

```sass
// this is a mixin for a simple test.
// should return a media query with a block nested into
test($min, $max)
  @media (min-width: $min) and (max-width: $max)
    {block}

// this behaves normally. Console outputs 
// 'non-mixin'
// '@media ((min-width: 200px)) and ((max-width: 400px))'
@media (min-width: 200px) and (max-width: 400px)
  .test
    color: blue
    p('non-mixin')
    p(current-media())

// calling the mixin written before. We expect two lines output in console:
// 'mixin'
// '@media ((min-width: ($min)) and (max-width: ($max)))'
// or
// '@media ((min-width: (200px)) and (max-width: (400px)))'
// but actually the output will be like
// 'mixin'
// ''
+test(200px,400px)
  .test
    color: red
    p('mixin')
    p(current-media())

// nested placeholders won't extend if the css selector has no other css properties
+test(200px,400px)
  $placeholder-200-400
    $background
      background-color: purple
  .test
    @extend $placeholder-200-400 $background
```

css output
```css
@media (min-width: 200px) and (max-width: 400px) {
  .test {
    color: #0074d9;
  }
}
@media (min-width: 200px) and (max-width: 400px) {
  .test {
    color: #ff4136;
  }
}

```

Thanks in advance and great job with this wonderful preprocessor!

P.S. i'm sooo sorry for my bad English.
