### ISSUE TITLE
Nested tag order in output

### ISSUE THREAD

**Issue by eddiemonge** [LearnBoost/stylus#1842]
```css
.aclass {
  color: red;

  &input {
    color: blue;
  }
}

// outputs 
.aclass {
  color: #f00;
}
.aclassinput {
  color: #00f;
}

// instead of
.aclass {
  color: #f00;
}
input.aclass {
  color: #00f;
}
```
