### ISSUE TITLE
@extend within media queries bug.

### ISSUE THREAD

**Issue by pexlator** [LearnBoost/stylus#1856]
```stylus
$foo
	color: red;
.bar
	color: black;

@media (min-width: 1000px)
  .baz 
  	@extend $foo;
  .bla
  	@extend .bar;
```

###### Result:

```css
.baz {
  color: #f00;
}
.bar,
.bla {
  color: #000;
}
```

###### Expected:
```css
.bar {
  color: black;
}

@media (min-width: 1000px) {

  .baz {
    color: red;
  }

  .bla {
    color: black;
  }
  
}
```
