### ISSUE TITLE
@extend bugs in block mixins

### ISSUE THREAD

**Issue by firede** [LearnBoost/stylus#1862]
Source:
```styl
foo()
  .lol
    {block}
.foo
  height: 40px

.bar
  +foo()
    @extend .foo
```

Output:
```css
.foo,
.bar {
  height: 40px;
}
```

Expect:
```css
.foo,
.bar .lol {
  height: 40px;
}
```

_version: 0.50.0_
