### ISSUE TITLE
@extend in sub-block of placeholder selector doesn't ouput

### ISSUE THREAD

**Issue by donut** [LearnBoost/stylus#1864]
For example, I would expect the Stylus code

```stylus
$purdy
  color red

$big-thing
  background gray
  a:visited
    @extends $purdy

.best-thing
  @extends $big-thing
```

to compile to

```css
.best-thing {
  background: #808080;
}

.best-thing a:visited {
  color: #f00;
}
```

but it comes out as 

```css
.best-thing {
  background: #808080;
}
```

completely missing the `a:visited` block. Is there any way around this?
